'use strict';
// Expected prescriptions transcribed from Revision 6, not generated by PROGRAM.
// Source identity and the observation-dependent clauses are in PROGRAM-CONFORMANCE.md.
const test = require('node:test');
const assert = require('node:assert/strict');
const { PROGRAM: P } = require('../js/program');
const { MODEL: M } = require('../js/model');
const cfg = (week = 3, extra = {}) => ({
  ...P.defaults(),
  onboarding: false,
  entryStage: 3,
  week,
  phaseGate: 'R',
  ...extra,
});
const rows = (t, day, ctx = {}) =>
  P.dayPlan(t, day, ctx)
    .sessions.filter((s) => !s.skipped)
    .flatMap((s) => s.rows);
const quality = (t, day, ctx) => rows(t, day, ctx).filter((e) => e.kind === 'quality');
const record = (t, day, session = 'main', at = 1000) => {
  const s = P.dayPlan(t, day).sessions.find((s) => s.id === session);
  return {
    revision: 6,
    day,
    startedAt: at,
    endedAt: at + 100,
    session: s,
    context: { level: 'green', event: 'normal', recovery: t.recovery },
    recoveryNormal: true,
    recoveryConfirmed: true,
    omitted: [],
    sets: s.rows.flatMap((e) =>
      Array.from({ length: e.kind === 'quality' ? M.qualityState(e, []).planned : e.sets }, () => ({
        exerciseId: e.id,
        exerciseKey: e.key,
        weight: 100,
        reps: e.repRange?.[1] || 1,
        endpoint: 'failure',
        outcome: 'make',
        grade: 'A',
        effort: 6,
      })),
    ),
  };
};

test('p7: all twelve ordinary Olympic day templates match literal F/B/R table', () => {
  const expected = {
    3: {
      monday: [
        [6, 2, [65, 75]],
        [3, '1+1', [60, 70]],
      ],
      tuesday: [
        [6, '1+1', [65, 75]],
        [3, 2, [55, 65]],
      ],
      thursday: [
        [6, 1, [70, 80]],
        [3, 2, [75, 85]],
        [2, 3, [90, 100]],
      ],
      friday: [
        [4, 1, [75, 85]],
        [4, '1+1', [75, 85]],
      ],
    },
    6: {
      monday: [
        [6, 2, [70, 80]],
        [3, '1+1', [65, 75]],
      ],
      tuesday: [
        [6, '1+1', [72, 82]],
        [3, 2, [60, 70]],
      ],
      thursday: [
        [5, 1, [75, 85]],
        [4, 1, [85, 95]],
        [2, 3, [95, 105]],
      ],
      friday: [
        [4, 1, [80, 90]],
        [4, '1+1', [80, 90]],
      ],
    },
    10: {
      monday: [
        [5, 1, [78, 85]],
        [3, '1+1', [70, 78]],
      ],
      tuesday: [
        [5, '1+1', [78, 85]],
        [3, 1, [65, 75]],
      ],
      thursday: [
        [4, 1, [75, 82]],
        [3, 1, [90, 100]],
      ],
      friday: [
        [4, 1, [80, 90]],
        [4, '1+1', [80, 90]],
      ],
    },
  };
  for (const [week, days] of Object.entries(expected))
    for (const [day, want] of Object.entries(days)) {
      const t = cfg(Number(week), { anchors: { snatch: 155, cj: 205, jerk: 215 } });
      assert.deepEqual(
        quality(t, day).map((e) => [e.sets, e.reps, e.range]),
        want,
        week + ' ' + day,
      );
    }
  assert.deepEqual(quality(cfg(6), 'friday')[0].sequence, [
    [80, 80],
    [85, 85],
    [88, 88],
    [88, 90],
  ]);
  assert.deepEqual(quality(cfg(10), 'friday')[0].sequence, [
    [80, 80],
    [85, 85],
    [88, 90],
    [90, 90],
  ]);
});
test('taper table: exact Tuesday/Thursday rests and 8–10 minute inter-lift transition', () => {
  const t = cfg(12);
  assert.deepEqual(
    quality(t, 'monday').map((e) => [e.sets, e.range, e.effort, e.rest]),
    [
      [3, [75, 80], 7, 150],
      [3, [75, 80], 7, 150],
    ],
  );
  assert.deepEqual(
    quality(t, 'tuesday').map((e) => [e.sets, e.range, e.effort, e.rest]),
    [
      [2, [80, 85], 8, 180],
      [2, [80, 85], 8, 180],
    ],
  );
  assert.deepEqual(
    quality(t, 'thursday').map((e) => [e.sets, e.range, e.effort, e.rest]),
    [
      [2, [50, 60], 6, 120],
      [2, [50, 60], 6, 120],
    ],
  );
  assert.equal(quality(t, 'friday')[0].afterRest, 540);
  for (const [day, range, min, max] of [
    ['monday', [3, 5], 240, 300],
    ['saturday', [6, 8], 180, 240],
  ]) {
    const e = rows(t, day).find((e) => e.id === 'bench');
    assert.deepEqual(e.repRange, range);
    assert.ok(e.rest >= min && e.rest <= max);
  }
});
test('p16: every technique menu produces the prescribed replacement, not extra failure work', () => {
  const one = (tech, day, id) => quality(cfg(3, { technique: tech }), day).find((e) => e.id === id);
  let e = one({ snatch: 'receive' }, 'monday', 'snatch');
  assert.deepEqual([e.sets, e.reps, e.range, e.effort, e.rest], [3, 3, null, 4, 90]);
  assert.match(e.note, /2 s pause/);
  e = one({ clean: 'return' }, 'monday', 'cj');
  assert.deepEqual([e.sets, e.range, e.rest], [4, [40, 60], 120]);
  e = one({ snatch: 'turnover' }, 'tuesday', 'hang');
  assert.deepEqual([e.sets, e.reps, e.range], [3, 2, [40, 60]]);
  assert.match(e.name, /High-hang/);
  e = one({ clean: 'turnover' }, 'monday', 'cj');
  assert.deepEqual([e.sets, e.reps, e.range], [3, '1+1', [40, 60]]);
  const balance = quality(cfg(3, { technique: { snatch: 'balance' } }), 'monday').filter(
    (e) => e.id === 'snatch',
  );
  assert.deepEqual(
    balance.map((e) => [e.sets, e.reps, e.range]),
    [
      [2, 1, [50, 65]],
      [4, 2, [65, 65]],
    ],
  );
  assert.equal(balance[0].rest, 120);
  assert.match(balance[0].note, /2 s/);
  for (const mode of ['stance', 'dip']) {
    e = one({ jerk: mode }, 'thursday', 'pause_jerk');
    assert.deepEqual([e.sets, e.reps, e.effort, e.rest], [3, 2, 6, 90]);
    assert.match(e.note, /split 2 s/);
  }
});
test('p16 vs p31: light pause-dip regression remains distinct from assessed-RJ assistance', () => {
  const trial = { kind: 'pause_jerk', day: 'thursday', startedAt: 1 };
  let t = cfg(6, { trial }),
    e = quality(t, 'thursday').find((e) => e.id === 'pause_jerk');
  assert.deepEqual(
    [e.sets, e.reps, e.range, e.anchor, e.rest, e.effort],
    [3, 2, [40, 60], 'cj', 90, 6],
  );
  t.anchors.jerk = 210;
  e = quality(t, 'thursday').find((e) => e.id === 'pause_jerk');
  assert.deepEqual(
    [e.sets, e.reps, e.range, e.anchor, e.rest, e.effort],
    [2, 1, [60, 75], 'jerk', 180, 7],
  );
  t.technique = { jerk: 'dip' };
  e = quality(t, 'thursday').find((e) => e.id === 'pause_jerk');
  assert.deepEqual(
    [e.sets, e.reps, e.range, e.anchor, e.rest, e.effort],
    [3, 2, [40, 60], 'jerk', 90, 6],
  );
  assert.equal(quality(t, 'thursday').filter((e) => e.id === 'pause_jerk').length, 1);
});
test('p32: trial identity survives taper and pivot; resume requires a deliberate readiness review', () => {
  let t = cfg(11, {
    trial: { kind: 'press', day: 'friday', startedAt: 123, baseline: 'fixation' },
    established: [{ kind: 'set', exercise: 'shrug', day: 'tuesday', startedAt: 124 }],
  });
  t = M.reviewAdvance(t, { action: 'advance', green: true, realizationReady: true });
  assert.equal(t.trial.startedAt, 123);
  assert.equal(t.trial.paused, true);
  assert.equal(t.established[0].paused, true);
  t = M.reviewAdvance(t, { action: 'advance', green: true });
  t = M.reviewAdvance(t, { action: 'advance', green: true });
  assert.equal(t.week, 1);
  assert.equal(t.trial.startedAt, 123);
  assert.equal(t.trial.baseline, 'fixation');
  assert.ok(!rows(t, 'friday').some((e) => e.id === 'press'));
  t.trial.paused = false;
  assert.ok(rows(t, 'friday').some((e) => e.id === 'press'));
});
test('p32: held assistance never suggests progression; reduction still works', () => {
  for (const kind of ['press', 'squat', 'calf_partial', 'set'])
    for (const week of [4, 8, 9, 10]) {
      const t = cfg(week, { trial: { kind, day: 'friday', exercise: 'shrug', startedAt: 1 } });
      const e = rows(t, 'friday').find((e) => e.assistance);
      const last = {
        normal: true,
        rows: Array.from({ length: e.sets }, () => ({
          weight: 100,
          reps: e.repRange[1] + 1,
          endpoint: 'failure',
        })),
      };
      assert.equal(P.nextLoad(e, [last, last]).action, 'hold', kind + ' week ' + week);
      last.rows[0].reps = 0;
      assert.equal(P.nextLoad(e, [last]).action, 'reduce');
    }
});
test('checkpoint/load hold uses actual secure history; reduced readiness cannot be raised by it', () => {
  const t = cfg(3);
  const r = record(t, 'monday');
  r.sets.forEach((s) => (s.weight = 110));
  const held = M.withHistoricalLoads(P.dayPlan({ ...t, week: 4 }, 'monday'), [r]);
  assert.deepEqual(P.loadRange(held.sessions[0].rows[0], t.anchors), [110, 110]);
  const amber = M.withHistoricalLoads(
    P.dayPlan({ ...t, week: 4 }, 'monday', { readiness: 'amber' }),
    [r],
  );
  assert.ok(P.loadRange(amber.sessions[0].rows[0], t.anchors)[1] < 110);
});
test('recovery return restores +1 per successful row exposure, with no jump back to 4 laterals', () => {
  const t = cfg(6, { recovery: 'targeted' }),
    r = record(t, 'tuesday');
  const restored = { ...t, recovery: 'restore' };
  let ctx = M.historyContext(restored, [r], 'tuesday');
  let es = rows(restored, 'tuesday', ctx);
  assert.equal(es.find((e) => e.id === 'lateral').sets, 3);
  assert.equal(es.find((e) => e.id === 'incline').sets, 3);
  assert.equal(es.find((e) => e.id === 'row').sets, 2);
  r.recoveryConfirmed = false;
  ctx = M.historyContext(restored, [r], 'tuesday');
  assert.equal(rows(restored, 'tuesday', ctx).find((e) => e.id === 'lateral').sets, 2);
  const taper = rows({ ...restored, week: 12 }, 'tuesday', ctx);
  assert.ok(taper.every((e) => e.kind === 'quality' && e.sets <= 2));
});
test('source alternatives keep failure dose but reset comparability and allow the relevant squat', () => {
  const t = cfg(6, {
    incline: 'db',
    legCurl: 'lying',
    crunch: 'cable',
    supportedRow: 'machine',
    trial: { kind: 'squat', day: 'friday', squat: 'front_squat' },
  });
  const es = rows(t, 'friday');
  assert.match(es.find((e) => e.id === 'incline').name, /DB/);
  assert.match(es.find((e) => e.id === 'leg_curl').name, /Lying/);
  assert.equal(es.find((e) => e.key === 'squat_support').id, 'front_squat');
  assert.notEqual(
    M.fingerprint(es.find((e) => e.id === 'incline')),
    M.fingerprint(rows(cfg(6), 'friday').find((e) => e.id === 'incline')),
  );
});
test('athletics alternate earned variations and step down after >14 days for two good exposures', () => {
  const t = cfg(6, {
    athletics: {
      enabled: true,
      stage: 7,
      day: 'monday',
      secondary: 0,
      variation: 'fly',
      variationEffort: 90,
    },
  });
  let r = record(t, 'monday', 'field', 1),
    ctx = M.historyContext(t, [r], 'monday', 1000);
  assert.equal(ctx.variationExposure, false);
  assert.ok(!rows(t, 'monday', ctx).some((e) => e.id === 'fly'));
  const after = 16 * 86400000;
  ctx = M.historyContext(t, [r], 'monday', after);
  assert.equal(ctx.athleticReturn, true);
  assert.equal(rows(t, 'monday', ctx).find((e) => e.id === 'sprint').sets, 3);
  const r2 = record(t, 'monday', 'field', after);
  ctx = M.historyContext(t, [r, r2], 'monday', after + 1000);
  assert.equal(ctx.athleticReturn, true);
  const r3 = record(t, 'monday', 'field', after + 7 * 86400000);
  ctx = M.historyContext(t, [r, r2, r3], 'monday', after + 7 * 86400000 + 1000);
  assert.equal(ctx.athleticReturn, false);
  const taper = rows({ ...t, week: 11 }, 'monday', { variationExposure: true });
  assert.deepEqual(
    taper.filter((e) => e.kind === 'speed').map((e) => [e.id, e.sets]),
    [
      ['jump', 3],
      ['sprint', 1],
      ['fly', 1],
    ],
  );
});
test('events: verification removes extra-heavy work; completed games keep rehearsals separate; fixed game omits failure', () => {
  const t = cfg(10, {
    heavy: { snatch: 95, cj: 95, extraSnatch: 3, extraCj: 3 },
    athletics: { enabled: true, stage: 0, day: 'monday', variation: 'none' },
  });
  const v = rows(t, 'friday', { event: 'verification' });
  assert.ok(
    v.filter((e) => e.kind === 'quality').every((e) => !e.test && !e.sequence && e.range[1] <= 80),
  );
  assert.ok(v.filter((e) => e.kind === 'failure').every((e) => e.sets === 1));
  assert.ok(rows(t, 'monday', { event: 'verification' }).some((e) => e.id === 'jump'));
  const g = P.dayPlan(t, 'monday', { event: 'game', gameRehearsal: true });
  assert.equal(g.sessions[0].skipped, true);
  const rehearsal = g.sessions.find((s) => s.id === 'rehearsal');
  assert.ok(rehearsal.rows.every((e) => e.sets <= 3 && e.range[1] === 60 && e.rest === 120));
  assert.ok(rows(t, 'tuesday', { event: 'fixed_game_ol' }).every((e) => e.kind === 'quality'));
  assert.ok(!rows(cfg(12), 'saturday', { event: 'larger_later' }).some((e) => e.id === 'bench'));
});
test('combined phase/recovery/regression rules never restore omitted conventional work or exceed the selected technique effort', () => {
  for (let week = 1; week <= 13; week++)
    for (const recovery of ['normal', 'targeted', 'reset', 'restore'])
      for (const readiness of ['green', 'amber', 'red']) {
        const t = cfg(week, {
          recovery,
          technique: { snatch: 'receive', jerk: 'dip' },
          trial: { kind: 'press', day: 'friday' },
        });
        for (const day of P.days) {
          const es = rows(t, day, { readiness });
          if (readiness === 'red') assert.equal(es.length, 0);
          if (readiness === 'amber') assert.ok(es.every((e) => e.kind !== 'failure'));
          if (week === 12)
            assert.ok(es.filter((e) => e.kind === 'failure').every((e) => e.id === 'bench'));
          if (recovery === 'reset')
            assert.ok(es.filter((e) => e.kind === 'failure').every((e) => e.id === 'bench'));
          assert.ok(es.filter((e) => e.name.includes('rehearsal')).every((e) => e.effort <= 4));
          assert.equal(new Set(es.map((e) => e.key)).size, es.length);
        }
      }
});

test('broad reduction and verification cap a repeated squat/calf exercise across assistance rows', () => {
  for (const context of [{ event: 'verification' }, { localIssue: 'upper' }, {}])
    for (const recovery of ['targeted', 'reset']) {
      const t = cfg(6, {
        recovery,
        assessment: 'clean',
        trial: { kind: 'squat', day: 'tuesday', squat: 'front_squat' },
        established: [{ kind: 'calf_partial', day: 'tuesday' }],
      });
      const es = rows(t, 'tuesday', context);
      assert.ok(!es.some((e) => e.key === 'squat_support' || e.assessment || e.id === 'clean'));
      assert.ok(es.filter((e) => e.id === 'calf').reduce((n, e) => n + e.sets, 0) <= 1);
    }
});
test('same named machine with a changed setup starts a fresh comparison without deleting history', () => {
  const previous = rows(cfg(), 'tuesday').find((e) => e.id === 'incline');
  const changed = rows(cfg(3, { setupEpoch: { incline: 123 } }), 'tuesday').find(
    (e) => e.id === 'incline',
  );
  assert.notEqual(M.fingerprint(previous), M.fingerprint(changed));
  assert.deepEqual([previous.sets, previous.repRange], [changed.sets, changed.repRange]);
});
